name: words
on: [push, pull_request]
jobs:
  vale:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Vale
        run: brew install vale

      - name: Run Vale
        run: vale .

